awinooliyo/AirBnB_clone_v3

models/engine/db_storage.py
models/engine/file_storage.py

Made updates to FileStorage and DBstorage with check and count methods.

Updating DBStorage and FileStorage

---

tests/test_models/test_engine/test_db_storage.py
tests/test_models/test_engine/test_file_storage.py

The respective tests

---

models/engine/db_storage.py

Fixing errors further

---

api/v1/app.py
api/v1/views/__init__.py
api/v1/views/index.py

Status of your API

---

api/v1/views/index.py

Pep 8 compliance

---

api/v1/views/index.py

Some stats

---

api/v1/views/index.py

Some stats added

---

api/v1/app.py

404 Error Redirect

---

api/v1/app.py

fixing error redirect

---

api/v1/app.py

import error fixed

---

api/v1/views/__init__.py
api/v1/views/states.py

States View

---

api/v1/views/states.py

minor changes

---

api/v1/views/states.py

updating and correcting errors

---

api/v1/views/states.py

fixing more errors

---

api/v1/views/states.py

modifying updated to add hasatt()

modifying updated to add hasatt()

---

api/v1/views/states.py

trying again

---

api/v1/views/states.py

cant check still

---

api/v1/views/states.py

Fixed create and delete routes.

Fixing a few errors

---

api/v1/views/index.py

stats fiexed

---

api/v1/views/states.py

Refactoring code

---

api/v1/views/__init__.py
api/v1/views/cities.py

question 7 - city

---

api/v1/views/cities.py

fixed create

---

api/v1/views/cities.py

fixed get cities

---

api/v1/views/cities.py

Fixed created

---

api/v1/views/__init__.py
api/v1/views/amenities.py

question 8 - amenities

---

api/v1/views/__init__.py
api/v1/views/amenities.py

Reverts awinooliyo/AirBnB_clone_v3#43

Revert "Revert "question 8 - amenities""

---

api/v1/views/amenities.py

fixed errors

---

api/v1/views/cities.py

changes to check

---

api/v1/views/__init__.py
api/v1/views/users.py

question 9 - users

---

api/v1/views/amenities.py
api/v1/views/users.py

Storage get count

---

api/v1/views/amenities.py
api/v1/views/cities.py

fixed 7 and 8

---

api/v1/views/amenities.py

amenities fix
